#!/usr/bin/env node
/**
 * HTML Timeline Exporter
 * Generates interactive HTML visualization from heartbeat data
 */

const fs = require('fs');
const path = require('path');

function parseArgs() {
    const args = process.argv.slice(2);
    const config = {
        input: './data/heartbeats.json',
        output: './output/timeline.html'
    };
    
    for (let i = 0; i < args.length; i++) {
        if (args[i] === '--input' || args[i] === '-i') config.input = args[++i];
        if (args[i] === '--output' || args[i] === '-o') config.output = args[++i];
    }
    
    return config;
}

function getModeEmoji(mode) {
    const emojis = {
        manager: '🎯',
        executor: '🔨',
        reviewer: '📋'
    };
    return emojis[mode] || '📌';
}

function getModeColor(mode) {
    const colors = {
        manager: '#3498db',
        executor: '#27ae60',
        reviewer: '#9b59b6'
    };
    return colors[mode] || '#95a5a6';
}

function generateHTML(data, config) {
    const heartbeats = data.heartbeats || [];
    const okrs = data.okrs?.key_results || {};
    
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agent Heartbeat Timeline</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #1a1a2e; color: #eee; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { text-align: center; margin-bottom: 10px; color: #00d9ff; }
        .subtitle { text-align: center; color: #888; margin-bottom: 30px; }
        .okr-section { background: #16213e; border-radius: 10px; padding: 20px; margin-bottom: 30px; }
        .okr-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-top: 15px; }
        .okr-card { background: #1a1a2e; padding: 15px; border-radius: 8px; border-left: 4px solid #00d9ff; }
        .okr-card h3 { color: #00d9ff; margin-bottom: 10px; }
        .progress-bar { background: #333; border-radius: 10px; height: 20px; overflow: hidden; margin: 10px 0; }
        .progress-fill { height: 100%; background: linear-gradient(90deg, #00d9ff, #00ff88); transition: width 0.3s; }
        .timeline { position: relative; padding-left: 30px; }
        .timeline::before { content: ''; position: absolute; left: 10px; top: 0; bottom: 0; width: 2px; background: #333; }
        .heartbeat { position: relative; margin-bottom: 15px; padding: 15px; background: #16213e; border-radius: 8px; }
        .heartbeat::before { content: ''; position: absolute; left: -24px; top: 20px; width: 12px; height: 12px; border-radius: 50%; background: #00d9ff; border: 2px solid #1a1a2e; }
        .heartbeat-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }
        .heartbeat-mode { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }
        .heartbeat-time { color: #888; font-size: 14px; }
        .heartbeat-task { font-weight: bold; margin-bottom: 5px; }
        .heartbeat-output { color: #aaa; font-size: 14px; }
        .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin-top: 20px; }
        .stat-card { background: #16213e; padding: 15px; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 24px; font-weight: bold; color: #00d9ff; }
        .stat-label { color: #888; font-size: 14px; margin-top: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🤖 Agent Heartbeat Timeline</h1>
        <p class="subtitle">Autonomously generated by AI agent</p>
        
        <div class="okr-section">
            <h2>📊 OKR Progress</h2>
            <div class="okr-grid">
                ${Object.entries(okrs).map(([kr, info]) => `
                    <div class="okr-card">
                        <h3>${kr}</h3>
                        <p>${info.current}/${info.target} ${info.unit}</p>
                        <div class="progress-bar">
                            <div class="progress-fill" style="width: ${Math.min(100, info.current/info.target*100)}%"></div>
                        </div>
                    </div>
                `).join('')}
            </div>
        </div>
        
        <div class="stats">
            <div class="stat-card">
                <div class="stat-value">${heartbeats.length}</div>
                <div class="stat-label">Total Heartbeats</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">${heartbeats.filter(h => h.mode === 'manager').length}</div>
                <div class="stat-label">🎯 Manager</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">${heartbeats.filter(h => h.mode === 'executor').length}</div>
                <div class="stat-label">🔨 Executor</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">${heartbeats.filter(h => h.mode === 'reviewer').length}</div>
                <div class="stat-label">📋 Reviewer</div>
            </div>
        </div>
        
        <h2 style="margin: 30px 0 20px;">📈 Timeline</h2>
        <div class="timeline">
            ${heartbeats.map(hb => `
                <div class="heartbeat" style="border-left: 3px solid ${getModeColor(hb.mode)}">
                    <div class="heartbeat-header">
                        <span class="heartbeat-mode" style="background: ${getModeColor(hb.mode)}20; color: ${getModeColor(hb.mode)}">
                            ${getModeEmoji(hb.mode)} ${hb.mode}
                        </span>
                        <span class="heartbeat-time">#${hb.number} · ${new Date(hb.timestamp).toLocaleString()}</span>
                    </div>
                    <div class="heartbeat-task">${hb.task || 'No task'}</div>
                    <div class="heartbeat-output">${hb.output || ''}</div>
                </div>
            `).join('')}
        </div>
    </div>
</body>
</html>`;
    
    return html;
}

function main() {
    const config = parseArgs();
    
    if (!fs.existsSync(config.input)) {
        console.error(`Error: Input file not found: ${config.input}`);
        process.exit(1);
    }
    
    const data = JSON.parse(fs.readFileSync(config.input, 'utf8'));
    const html = generateHTML(data, config);
    
    const outputDir = path.dirname(config.output);
    if (outputDir && !fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }
    
    fs.writeFileSync(config.output, html);
    console.log(`✓ HTML timeline generated: ${config.output}`);
}

main();
